### ISSUE TITLE
non cli api

### ISSUE THREAD

**Issue by jonstuebe** [jwagner/smartcrop-cli#5]
Is there a version of this for node usage that doesn't require using a cli?

**Comment by jwagner** [comment]
Of the cli - no. Of the library - yes - it's in the canvas-independence branch. I hope that helps. I still have to figure out what to do with the CLI. I could continue to just use node-canvas (not really a great option), just depend on imagemagick/graphicsmagick (a bit better) or make it more generic so at least *magick and vips (via sharp) would be supported. I'm tempted to go with *magick just because it's simple and works on most linux boxes without much trouble. What would you prefer?

**Comment by jonstuebe** [comment]
@jwagner I would prefer imagemagick as it's widely available. I put together a [quick fix](https://github.com/jonstuebe/smartcrop-node) for a project I'm working on right now, but I'm with you, I would rather not have to rely on node-canvas down the line.

**Comment by jwagner** [comment]
Thank you! :)
